create table if not exists public.wallets (
  id bigint generated by default as identity primary key,
  balance numeric(12, 2) not null default 0,
  currency text not null default 'INR',
  pin_hash text,
  pin_salt text,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  title text not null,
  recipient text,
  amount numeric(12, 2) not null,
  direction text not null check (direction in ('in', 'out')),
  created_at timestamptz not null default now()
);

create table if not exists public.loan_applications (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null,
  purpose text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- Safe to re-run: adds the PIN columns even if the table already existed before this change.
alter table public.wallets add column if not exists pin_hash text;
alter table public.wallets add column if not exists pin_salt text;

insert into public.wallets (balance, currency)
select 25000, 'INR'
where not exists (select 1 from public.wallets);

alter table public.wallets enable row level security;
alter table public.transactions enable row level security;
alter table public.loan_applications enable row level security;

create policy "Paisa Voice can read wallets"
  on public.wallets for select using (true);
create policy "Paisa Voice can read transactions"
  on public.transactions for select using (true);
create policy "Paisa Voice can insert transactions"
  on public.transactions for insert with check (true);
create policy "Paisa Voice can insert loan applications"
  on public.loan_applications for insert with check (true);